{% set version = "0.1" %}
{% set sha256 = "6e9eb0dd85ce0b728fb9595cdadd70f6f3d2326cad3eb73e96bad5c2d5fb11c2" %}

package:
  name: odgi
  version: '{{version}}'

source:
  git_url: https://github.com/vgteam/odgi/
  git_tag: conda
  sha256: '{{sha256}}'

build:
  skip: True  # [osx or py27]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - cmake
  host:
    - zlib
    - python
  run: 
    - llvm-openmp  # [osx]
    - python
    - zlib

test:
  commands:
    - odgi test
  imports:
    - odgi

about:
  home: https://github.com/vgteam/odgi
  license: MIT
  summary: An optimized dynamic genome graph implementation

extra:
  skip-lints:
    - uses_vcs_url
